name: Testing-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: npm 7
        run: npm i -g npm@7 --registry=https://registry.npmjs.org

      - name: Install
        run: |
          npm install
          npm run bootstrap

      - name: Test
        run: npm test
